-- Migration: 0001_initial
-- Generated by: npx drizzle-kit generate
-- Applied by:   npx drizzle-kit migrate
--
-- REVIEW THIS FILE before applying to production.
-- Drizzle tracks applied migrations in the __drizzle_migrations table.

-- ── USERS ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "users" (
  "id"         SERIAL       PRIMARY KEY NOT NULL,
  "name"       VARCHAR(100)             NOT NULL,
  "email"      VARCHAR(255)             NOT NULL,
  "created_at" TIMESTAMP    DEFAULT now() NOT NULL,
  "updated_at" TIMESTAMP    DEFAULT now() NOT NULL,
  CONSTRAINT "users_email_unique" UNIQUE ("email")
);

-- ── TASKS ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "tasks" (
  "id"          SERIAL       PRIMARY KEY NOT NULL,
  "title"       VARCHAR(255)             NOT NULL,
  "description" TEXT,                              -- nullable
  "completed"   BOOLEAN      DEFAULT false NOT NULL,
  "user_id"     INTEGER                   NOT NULL,
  "created_at"  TIMESTAMP    DEFAULT now() NOT NULL,
  "updated_at"  TIMESTAMP    DEFAULT now() NOT NULL
);

-- ── FOREIGN KEY ────────────────────────────────────────────────────────────
-- ON DELETE CASCADE: deleting a user automatically deletes all their tasks

ALTER TABLE "tasks"
  ADD CONSTRAINT "tasks_user_id_users_id_fk"
  FOREIGN KEY ("user_id")
  REFERENCES "users" ("id")
  ON DELETE CASCADE
  ON UPDATE NO ACTION;
